server:
  port: 8081
spring:
  datasource:
    #driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password: 123456
  application:
    name:  user-service
mybatis:
  type-aliases-package:  cn.itcast.user.pojo
eureka:
  client:
    service-url:
      defaultZone : http://127.0.0.1:10086/eureka  #注册地址，自己也注册进去,注册进eureka集群
  instance:
    prefer-ip-address: true #希望使用IP地址
    ip-address: 127.0.0.1    #把IP地址写死
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
logging:
  level:
    c.n : debug