server:
  port: 8088
spring:
  application:
    name:  consumer-service
eureka:
  client:
    service-url:
      defaultZone : http://127.0.0.1:10086/eureka  #注册地址，自己也注册进去,注册进eureka集群
  instance:
    prefer-ip-address: true #希望使用IP地址
    ip-address: 127.0.0.1    #把IP地址写死
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
ribbon:
  ConnectionTimeOut: 500
  ReadTimeOut: 2000